### ISSUE TITLE
Sanctum\HasApiTokens Trait Is Not Removed From User Model

### ISSUE THREAD

**Issue by danialrp** [aimeos/aimeos-headless#1]
Based on switching from sanctum auth which using the Laravel web auth driver (headful) to JWT, after logging in to admin panel, a not found exception throwing. 
This exception referring to `Trait "Laravel\Sanctum\HasApiTokens" not found`
By removing this trait from user model, seems JQ admin is working as normal but not sure about the JS admin as we are not using it.
i preferred to share this through an issue instead of a PR.

Tnx.
Danial from Kappa Team.

**Comment by aimeos** [comment]
This can be removed because we aren't using API tokens in the backend. Can you create a PR?

**Comment by danialrp** [comment]
Thanks for the reply.
Sure.
